alter table public.properties
  add column if not exists uso_comercial text,
  add column if not exists saldo_banco text,
  add column if not exists saldo_banco_moneda text default 'USD',
  add column if not exists oferta text,
  add column if not exists financia text,
  add column if not exists renta text,
  add column if not exists porcentaje_renta numeric,
  add column if not exists habilitada_banco text,
  add column if not exists comentario_venta text,
  add column if not exists acepta_mascota text,
  add column if not exists acepta_fumador text,
  add column if not exists acepta_ninos text,
  add column if not exists suites integer,
  add column if not exists toilette text,
  add column if not exists living text,
  add column if not exists comedor text,
  add column if not exists living_comedor text,
  add column if not exists comedor_diario text,
  add column if not exists cocina text,
  add column if not exists cap_personas integer,
  add column if not exists cantidad_camas integer,
  add column if not exists dep_servicio text,
  add column if not exists estufa_lena text,
  add column if not exists playroom text,
  add column if not exists parrillero text,
  add column if not exists lavadero text,
  add column if not exists calefaccion text,
  add column if not exists despensa text,
  add column if not exists muebles text,
  add column if not exists amoblada text,
  add column if not exists adaptada_movilidad text,
  add column if not exists clave_wifi text,
  add column if not exists estado_propiedad_detalle text,
  add column if not exists precio_venta_moneda text default 'USD',
  add column if not exists precio_libre_moneda text default 'USD',
  add column if not exists precio_tasacion_moneda text default 'USD',
  add column if not exists precio_portales_moneda text default 'USD';

update public.properties
set
  precio_venta_moneda = coalesce(precio_venta_moneda, 'USD'),
  precio_libre_moneda = coalesce(precio_libre_moneda, 'USD'),
  precio_tasacion_moneda = coalesce(precio_tasacion_moneda, 'USD'),
  precio_portales_moneda = coalesce(precio_portales_moneda, 'USD'),
  saldo_banco_moneda = coalesce(saldo_banco_moneda, 'USD');
