alter table public.properties
  add column if not exists country text default 'Uruguay',
  add column if not exists comentario text,
  add column if not exists property_type_detail text,
  add column if not exists city text,
  add column if not exists barrio_zona text,
  add column if not exists manzana text,
  add column if not exists padron text,
  add column if not exists solar text,
  add column if not exists parada text,
  add column if not exists phone_number text,
  add column if not exists address text,
  add column if not exists door_number text,
  add column if not exists vista text,
  add column if not exists house_type text,
  add column if not exists orientacion text,
  add column if not exists disposicion text,
  add column if not exists distancia_mar_mts integer,
  add column if not exists frente_mar text,
  add column if not exists cartel text,
  add column if not exists precio_venta text,
  add column if not exists precio_alquiler text,
  add column if not exists en_venta text,
  add column if not exists en_alquiler text,
  add column if not exists estado_prop text,
  add column if not exists ambientes integer,
  add column if not exists dormitorios text,
  add column if not exists banos text,
  add column if not exists bano_servicio text,
  add column if not exists cochera text,
  add column if not exists garage text,
  add column if not exists plantas integer,
  add column if not exists sup_terreno numeric,
  add column if not exists sup_cubierta numeric,
  add column if not exists sup_semi_cubierta numeric,
  add column if not exists terraza text,
  add column if not exists propiedad_horizontal text,
  add column if not exists piscina text,
  add column if not exists precio_escritura text,
  add column if not exists precio_libre text,
  add column if not exists precio_tasacion text,
  add column if not exists vigencia_venta date,
  add column if not exists vigencia_alquiler date,
  add column if not exists precio_portales text,
  add column if not exists nota_alquiler text,
  add column if not exists permuta text,
  add column if not exists descripcion text,
  add column if not exists video_url text,
  add column if not exists matterport_url text;

update public.properties
set country = coalesce(country, 'Uruguay')
where country is null;